### ISSUE TITLE
Add support for many-to-many with composite through inner/outer keys

### ISSUE THREAD

**Issue by rauanmayemir** [cycle/schema-builder#25]
As part of the cycle v2's composite keys support, relations could also be linked via composite inner or outer keys.

Currently, schema builder [restricts ManyToMany through keys](https://github.com/cycle/schema-builder/blob/9de28bb35f8ec0cc05aa0f17643165e4238a9f8a/src/Relation/ManyToMany.php#L102) to a single field. This should be changed once V2 is out.

**Comment by roxblnfk** [comment]
The feature was added with ORM v2 release
